server:
  port: 8080
  servlet:
    context-path: /easy-flow

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easy_flow?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: xiaoka
    driver-class-name: com.mysql.jdbc.Driver

#mybatis
mybatis-plus:
  # mybatis xml配置文件扫描
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xioaka.easy.flow.sdk;